### ISSUE TITLE
is it possible to support css?

### ISSUE THREAD

**Issue by e-cloud** [leftstick/unminified-webpack-plugin#1]

**Comment by leftstick** [comment]
Normally, individual `css` file is handled via [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin), what you mean about "support"? Can you give me some use case?

**Comment by e-cloud** [comment]
sorry. What i mean is many libraries contain js and css, most of their csses also need two version output.
ETP is just extract the css from js. it doesn't handle like what you've done for js.
And i can't find a way to do that.
So i'm just seeking solution.

**Comment by leftstick** [comment]
So what you need is any extension of [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin)?

If you have example project, it would be better for me to understand your problem

**Comment by e-cloud** [comment]
nope. It's none of ETP's business.

Take `bootstrap` as example, it distributed its css with `bootstrap.css` and `bootstrap.min.css`.

It's related to css-loader. Its minimization works inside so that there is no extension point to extract the original(or preprocessed) source of css.

Perhaps i should a loader place between the css-loader and some other preprocessor loaders.

**Comment by e-cloud** [comment]
BTW, this plugin doesn't work well with webpack's `bannerPlugin` as it output the `js` file before `bannerPlugin` runs.
I think you should add the source to the compilation's assets but not output the file by yourself

**Comment by leftstick** [comment]
What you mean "doesn't work well with `bannerPlugin`"? Error? or no banner applied in non-minified file?

**Comment by e-cloud** [comment]
no banner applied to non-minified file.

**Comment by leftstick** [comment]
For "compilation's assets" part, i think it's very good idea. I have done the upgrade.

The `banner` issue is kind of limitation due to the way how `UglifyPlugin` and `BannerPlugin` work.

The thing is, both two plugins are checking for `chunk.files` for mutation. The only way to have `banner` in the output is add the non-minified version to `chunk.files`, but by doing that, `UglifyPlugin` will do the its work on the non-minified version as well(which is not we intent to do).

**Comment by leftstick** [comment]
@e-cloud , i just published a new version, maybe you want to give a try, see [css-pack](https://github.com/leftstick/unminified-webpack-plugin/blob/master/example/css-pack/README.md) for working example & configuration

**Comment by e-cloud** [comment]
looks like it's a good solution 👍.

**Comment by leftstick** [comment]
@e-cloud  and `BannerPlugin` shall be supported in latest version `1.4.0`
