### ISSUE TITLE
Option to include/exclude files

### ISSUE THREAD

**Issue by johannes-z** [leftstick/unminified-webpack-plugin#10]
How about an option that allows you to include or exclude files based on their name similar to the `UglifyJsPlugin`?

F.e. I'm building something like this: 

```js 
var entry = {
  // Polyfill
  polyfill: ['babel-polyfill', 'whatwg-fetch'],
  // Source
  source: ['./src/main.js']
  // Other
}
```

I always want the polyfill file to be minified, and don't need the unminified version.

For the `UglifyJsPlugin` it would look like this: 

```js
new webpack.optimize.UglifyJsPlugin({
  include: /polyfill.*/,
  // ...
)}
```

**Comment by leftstick** [comment]
It's actually supported, i forget to add test cases and documentation. Thanks for reminding. Doc just updated.

Please check the [readme](https://github.com/leftstick/unminified-webpack-plugin#configuration)
