### ISSUE TITLE
Support for webpack.BannerPlugin

### ISSUE THREAD

**Issue by fabioricali** [leftstick/unminified-webpack-plugin#11]
Not work with webpack.BannerPlugin

**Comment by leftstick** [comment]
It's limitation(last time i checked), and described in the [readme](https://github.com/leftstick/unminified-webpack-plugin/blob/master/README.md)

![screen shot 2017-07-10 at 9 26 08 am](https://user-images.githubusercontent.com/1059956/27999632-e3755818-6551-11e7-96c8-fa77da4422cb.png)

**Comment by leftstick** [comment]
@fabioricali `BannerPlugin` shall be supported in latest version `1.4.0`, you can give a try
