### ISSUE TITLE
[1.4.0] Unable to install on node v6.0

### ISSUE THREAD

**Issue by ankurk91** [leftstick/unminified-webpack-plugin#13]
Hi,

Glad to see banner plugin support on v1.4.
But i was unable to upgrade to 1.4 because you have restricted this package to node 8.
https://github.com/leftstick/unminified-webpack-plugin/blob/cae981348c1e2b27b4c1c15e6cfb0a14dc324b76/package.json#L13

Is it possible to install this package on node v6.
Node 8 is not LTS yet. Most of the users be using node 6.x LTS.
I found build was successful for node 6, [see](https://travis-ci.org/leftstick/unminified-webpack-plugin/jobs/285332694)

Thanks

**Comment by leftstick** [comment]
Good point, let me adjust later

**Comment by leftstick** [comment]
@ankurk91  done, please try `1.4.1`
