### ISSUE TITLE
Not support react app

### ISSUE THREAD

**Issue by minocoko** [leftstick/unminified-webpack-plugin#15]
When I add 
`new UnminifiedWebpackPlugin({
      postfix: 'all',//specify "nomin" postfix,
      include: /polyfill.*/,
      exclude: /test.*/
    }),`

into new react app path node_modules\react-scripts\config\webpack.config.prod.js
then run "yarn build", only two files created.

**Comment by leftstick** [comment]
If you are using `create-react-app`, your app isn't in the support list of this plugin.

![screen shot 2017-11-28 at 10 40 41 am](https://user-images.githubusercontent.com/1059956/33300611-4adc0710-d42c-11e7-8976-81c04a4bfc0b.png)

It was not designed for a complete application
