### ISSUE TITLE
Uncompressed filenames become folders for minified files

### ISSUE THREAD

**Issue by mrpsiho** [leftstick/unminified-webpack-plugin#16]
Hi,

Please, suggest. Maybe my configuration is wrong, but I am not sure how to solve this. What I have got is smth like this:

```
/js
- /front.js
-- front.min.js
```
I mean - there are two folders and one minified file.
Instead of:
```
/js
- front.js
- front.min.js
```
one folder and one uncompressed file and one minified.

**Comment by leftstick** [comment]
Please shoot your `webpack.config.js` and your file structure

**Comment by Scit** [comment]
This is an IDE issue, I think.
I see the same in Pycharm. `ls` directory in console gives the correct result.
