### ISSUE TITLE
Migration 5.1.0-5.1.1 is failing inputSource.sourceAndMap is not a function

### ISSUE THREAD

**Issue by ievgennaida** [leftstick/unminified-webpack-plugin#28]
The project cannot be migrated from v4 to the latest v5.
Problem is reproduced on update  5.1.0-5.1.1

Sources:

Webpack config:
```
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const UnminifiedWebpackPlugin = require('unminified-webpack-plugin');

//  devtool: 'inline-source-map',
module.exports = {
  mode: 'production',
  entry: {
    'animation-timeline': './src/animation-timeline.ts',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'babel-loader',
        exclude: [/node_modules/, /lib/],
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts'],
  },
  output: {
    filename: '[name].min.js',
    libraryTarget: 'umd',
    library: 'timelineModule',
    // eslint-disable-next-line no-undef
    path: path.resolve(__dirname, 'lib'),
  },
  plugins: [new UnminifiedWebpackPlugin()],
};
```

package.json
```
  "devDependencies": {
    "@babel/cli": "7.12.10",
    "@babel/core": "7.12.10",
    "@babel/plugin-proposal-class-properties": "7.12.1",
    "@babel/preset-env": "7.12.10",
    "@babel/preset-typescript": "7.12.7",
    "@types/chai": "4.2.14",
    "@types/mocha": "8.2.0",
    "@typescript-eslint/eslint-plugin": "4.9.1",
    "@typescript-eslint/parser": "4.9.1",
    "babel-loader": "8.2.2",
    "eslint": "7.15.0",
    "eslint-config-prettier": "7.0.0",
    "eslint-plugin-prettier": "3.2.0",
    "prettier": "2.2.1",
    "ts-loader": "8.0.12",
    "typescript": "4.1.3",
    "unminified-webpack-plugin": "2.0.0",
    "webpack": "4.44.2",
    "webpack-cli": "4.2.0"
  },

```

# Bug report

Exception when moving
HookWebpackError: inputSource.sourceAndMap is not a function
    at makeWebpackError (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\lib\Compilation.js:1997:11
    at eval (eval at create (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:39:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: inputSource.sourceAndMap is not a function
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\dist\index.js:323:27
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:23:31
    at run (C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:23:43)
    at C:\dev\Vector-editor\js-animation-timeline-control\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:45:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
caused by plugins in Compilation.hooks.processAssets

**What is the expected behavior?**

Migration plan or should not fail.

**Comment by leftstick** [comment]
@ievgennaida  will you provide a simple reproduce repo?

**Comment by ievgennaida** [comment]
I have removed package from my repo, but steps still can be reproduced if you will pickup commit before the migration to version 5.

1. Clone
https://github.com/ievgennaida/animation-timeline-control
2. Go to commit 
bcaac5eb88e662639972bf42d8bb736dcfb3ce24
3. Try to update webpack to version 5.1.1 or higher. 

It looks like some kind plugins conflict.

**Comment by leftstick** [comment]
@geforcesong would you mind checking this issue? Thanks

**Comment by DRiFTy17** [comment]
Was there any progress made on this? I'm also using this plugin and ran into this issue when upgrading to Webpack 5.

**Comment by leftstick** [comment]
@DRiFTy17  i am lacking of time to check on this issue right now. 
But PR is very welcome

**Comment by DRiFTy17** [comment]
I'm using a secondary minification step in my build pipeline for the time being, but I'll circle back and take a look when I get some free time.

**Comment by leftstick** [comment]
`webpack@5` should be supported now. Please try `3.0.0`
