### ISSUE TITLE
creating unminified file in dev mode

### ISSUE THREAD

**Issue by GhostGlitch** [leftstick/unminified-webpack-plugin#31]
I can't figure out how to get it to make an unminified file in development mode. either I set minification to anything in my config and get two minified files, or I don't set it and I only get the main file. It's possible that I'm just being dumb, but I can't figure this out.

**Comment by leftstick** [comment]
`webpack` should not run any of optimization while in `development` mode by default. check below doc


<img width="1187" alt="Screen Shot 2022-02-10 at 1 51 33 PM" src="https://user-images.githubusercontent.com/1059956/153346333-e4a90609-604c-452c-83e4-988bde02e5d3.png">


It means, if you enable `mode: 'development'`, the output should be unminified. It's nothing to do with `unminified-webpack-plugin`. You should check why you have unmiinified output first(with my plugin removed)
