### ISSUE TITLE
Strange output. Minified is way way larger than unminified?

### ISSUE THREAD

**Issue by cAstraea** [leftstick/unminified-webpack-plugin#5]
I dunno I think I'm doing something very wrong ? Anyone can offer some hints ? First time trying out webpack.
The same thing happens when using webpack -p 

This my webpack config
https://gist.github.com/cAstraea/502492ab6a42d4d1b3631ba45bb4da5e

![minified](https://cloud.githubusercontent.com/assets/13070662/18666557/1aaaa85a-7f35-11e6-8444-6f4679dfb413.png)

**Comment by leftstick** [comment]
I believe you forgot setting the system variable `NODE_ENV` to `production` while building?

The thing is, if you do that, the `inline-source-map` will be packaged in the minified version which make it bigger.

And you should not do like that for production build
